---
- hosts: all
  become: true
  pre_tasks:

  - name: Install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    changed_when: false

- hosts: Controller_node
  become: true
  roles:
    - Horizon
    - Neutron
    - Cinder

- hosts: Computer_node
  become: true
  roles:
    - Horizon
    - Neutron
    - Cinder


